#!/usr/bin/env python3
# gen-trampolines.py — emit the FFI_WASM32 trampoline switch body.
# One `call_indirect` per argument type-vector over {i32,i64,f32,f64}, bounded by
# MAX_ARGS_ALL_I32 (all-i32 reach, M=0) / MAX_ARGS_MIXED / MAX_NON_I32. wasm requires
# each indirect call's signature to be statically known, so signatures are enumerated
# here at build time (no JS host to synthesize them — see wasm32-raw-ffi.c rationale).
import itertools, sys

MAX_ARGS_ALL_I32 = 24
MAX_ARGS_MIXED   = 10
MAX_NON_I32      = 2

# arg class -> (C param type, loader expr template over avalue[i])
ARG = {
    0: ("u32",      "load_i32_arg(at[{i}], av[{i}])"),  # i32: int/ptr/subword
    1: ("uint64_t", "(*(uint64_t*)av[{i}])"),           # i64
    2: ("float",    "(*(float*)av[{i}])"),              # f32
    3: ("double",   "(*(double*)av[{i}])"),             # f64
}
# return class -> (C return type, store stmt using `r` and `rvalue`)
RET = {
    0: ("void",     None),
    1: ("u32",      "if (rvalue) *(ffi_arg*)rvalue = (ffi_arg)r;"),
    2: ("uint64_t", "if (rvalue) *(uint64_t*)rvalue = r;"),
    3: ("float",    "if (rvalue) *(float*)rvalue = r;"),
    4: ("double",   "if (rvalue) *(double*)rvalue = r;"),
}

def argvecs():
    # all-i32 (M=0) up to MAX_ARGS_ALL_I32
    for n in range(0, MAX_ARGS_ALL_I32 + 1):
        yield (0,) * n
    # >=1 non-i32, up to MAX_NON_I32, up to MAX_ARGS_MIXED
    for n in range(1, MAX_ARGS_MIXED + 1):
        for positions in itertools.chain.from_iterable(
                itertools.combinations(range(n), k) for k in range(1, MAX_NON_I32 + 1)):
            for kinds in itertools.product((1, 2, 3), repeat=len(positions)):
                vec = [0] * n
                for pos, kind in zip(positions, kinds):
                    vec[pos] = kind
                yield tuple(vec)

def key(rc, vec):
    av = 0
    for i, c in enumerate(vec):
        av |= c << (2 * i)
    return (rc << 40) | (len(vec) << 32) | av

def emit():
    print("/* GENERATED by gen-trampolines.py — do not edit. */")
    seen = set()
    for rc, (rtype, store) in RET.items():
        for vec in argvecs():
            k = key(rc, vec)
            if k in seen:      # all-i32 arity-0 collides across nothing; guard anyway
                continue
            seen.add(k)
            params = ",".join(ARG[c][0] for c in vec) or "void"
            loads  = ",".join(ARG[c][1].format(i=i) for i, c in enumerate(vec))
            cast   = f"{rtype} (*)({params})"
            call   = f"(({cast})fn)({loads})"
            print(f"case 0x{k:x}ULL: {{")
            if rtype == "void":
                print(f"  {call};")
            else:
                print(f"  {rtype} r = {call};")
                print(f"  {store}")
            print("  break; }")
    print(f"/* {len(seen)} trampolines */", file=sys.stderr)

if __name__ == "__main__":
    emit()
