# The guest activation script ($sys/activate), generated by Nix and run by the
# thin /init AFTER the store overlay is mounted and BEFORE `exec $sys/init`
# (busybox init). This is the NixOS stage-2 activation role, systemd-free:
#   - /run/current-system + sw  (the profile indirection inittab/profile use)
#   - /etc  = a per-file symlink tree with /etc/static indirection (setup-etc.pl
#            pattern, in shell): each $sys/etc/<f> -> /etc/static/<f> -> store.
#   - mutable runtime dirs (/var/log, /var/run, /tmp, /root) + utmp/wtmp (the
#     tmpfiles role; login(1) records sessions into utmp, wtmp is never auto-made)
# Takes the system path as $1 (the thin /init passes it). /bin/sh is NOT made
# here — it is baked into the initramfs and persists (run-in-place, no switch_root).
#
# writeText, NOT writeShellScript: writeShellScript embeds a bash store-path
# shebang, and in THIS repo `cross.bash` is the NATIVE host bash (deps-overlay
# maps bash/runtimeShell -> buildPackages), which would drag native bash+glibc
# (~50MB) into the guest closure. The thin /init runs this as `sh "$sys/activate"
# "$sys"`, so the shebang is cosmetic; busybox ash honours `set -eu`.
{ pkgs }:
pkgs.writeText "activate" ''
  #!/bin/sh
  set -eu
  sys="$1"

  # Profile indirection: inittab + /etc/profile reference /run/current-system/sw.
  mkdir -p /run
  ln -sfn "$sys" /run/current-system
  # $sys/sw -> the system profile (system.path); see toplevel.nix.

  # /etc as a symlink tree (NixOS setup-etc pattern). /etc/static -> the store
  # etc dir (atomic-switch indirection); each entry -> /etc/static/<name>.
  mkdir -p /etc
  ln -sfn "$sys/etc" /etc/static
  for f in "$sys"/etc/*; do
    name=$(basename "$f")
    ln -sfn "/etc/static/$name" "/etc/$name"
  done

  # Mutable runtime state (cannot live in the immutable store).
  mkdir -p /var/log /var/run /tmp /root
  : > /var/run/utmp
  : > /var/log/wtmp
''
