# The thin initramfs /init for the wasm guest, GENERATED by Nix and baked into
# .#wasm-initramfs. It is the only hand-shaped guest code, and it is irreducible:
# it must mount the served /nix store before anything in the store is reachable.
# Roles: mount pseudofs + pc's 9P exports, overlay the read-only served store
# with a ramfs upper -> /nix, run the closure's activation, then exec the
# closure's init. The toolchain (nix/clang/wasm-ld/cc/make) is part of the served
# closure now — on PATH via the system profile, no host-provided /opt/bin seam.
# Run-in-place: no switch_root (NOMMU; the initramfs ramfs stays the root, so the
# baked /bin/sh persists).
#
# 9P: trans=cb -> net/9p/trans_cb.c -> the JS 9P server. msize 512K = the kernel
# transport cap (P9_CB_MAXSIZE). Exports (boot.js): "/"=pc VFS, nixcache,
# nix=the served wasm-system closure (createNixClosureStore).
{ pkgs }:
pkgs.writeText "init" ''
  #!/bin/sh
  # busybox is on /bin (baked); call applets via PATH.
  export PATH=/bin:/sbin

  mount -t proc none /proc
  mount -t sysfs none /sys
  mount -t devtmpfs none /dev 2>/dev/null
  mkdir -p /dev/pts && mount -t devpts none /dev/pts 2>/dev/null

  M="trans=cb,version=9p2000.L,msize=524288"
  # cache=loose + ignoreqv route 9p reads through the page cache (buffered) instead
  # of netfs UNBUFFERED/direct reads. Direct reads call iov_iter_extract_pages /
  # get_user_pages on the user buffer, which fails EFAULT on this NOMMU/wasm guest
  # ("netfs: Couldn't get user pages (rc=-14)") — that broke `nix-env -iA`. Buffered
  # reads fill kernel page-cache pages then copy_to_user (works). cache=none (the
  # default) forces P9L_DIRECT; so does qid.version==0 (which the JS 9p servers
  # report) unless ignoreqv is set — hence BOTH. Read-only exports, so loose is safe.
  RO="$M,cache=loose,ignoreqv"

  # pc's VFS (user files) at /mnt/pc.
  mkdir -p /mnt/pc
  mount -t 9p -o "$M,aname=/" cb /mnt/pc 2>/dev/null || echo "pc: /mnt/pc 9p mount failed"

  # Nix binary cache (substituter for `nix-env -iA`), read-only.
  mkdir -p /nix-cache
  mount -t 9p -o "$RO,aname=nixcache" cb /nix-cache 2>/dev/null || true

  # The served wasm-system closure: real /nix store paths, read-only (9p) ->
  # overlay lower; ramfs upper makes /nix writable for nix-env. NOMMU has no
  # tmpfs, so the upper is ramfs (always available, backs the initramfs root).
  mkdir -p /mnt/nix-ro /run/nix-upper /run/nix-work /nix
  if mount -t 9p -o "$RO,aname=nix" cb /mnt/nix-ro 2>/dev/null; then
    mount -t overlay overlay \
      -o lowerdir=/mnt/nix-ro,upperdir=/run/nix-upper,workdir=/run/nix-work /nix \
      || { echo "pc: /nix overlay failed; falling back to ramfs /nix"; mkdir -p /nix/store; }
  else
    echo "pc: served store not mounted; booting empty ramfs /nix"
    mkdir -p /nix/store
  fi

  # Resolve + activate the system, then hand off to init. The whole toolchain
  # (nix + multi-call entry points, clang, wasm-ld, cc, make) is now part of the
  # activated system profile (/run/current-system/sw/bin, on PATH via /etc/profile)
  # — there is NO host-provided /opt/bin seam anymore.
  # The profile symlink is a DIRECT absolute pointer to the store path (one level;
  # see store-manifest.py), so a plain readlink resolves it — no `-f`/realpath
  # canonicalization (musl realpath corrupts long targets read over 9p/overlay).
  sys=$(readlink /nix/var/nix/profiles/system 2>/dev/null)
  if [ -n "$sys" ] && [ -e "$sys/init" ]; then
    sh "$sys/activate" "$sys"

    # Promote the autoconf-capable forkshell ash to /bin/sh (the initramfs bakes
    # busybox hush there). hush isn't POSIX-enough for autoconf: a package's
    # ./configure and the config.status it generates carry a `#!/bin/sh` shebang,
    # so they run under whatever /bin/sh is. The forkshell ash (NOMMU-safe
    # subshell/$()/pipeline/heredoc via serialize+re-exec) parses autoconf; hush
    # dies with "ambiguous redirect" / "syntax error at 'fi'". Relink after
    # activation, once the served closure (and its ash) is mounted. System
    # services invoke the profile-absolute busybox sh directly, so only
    # `#!/bin/sh` scripts and the interactive login shell pick up ash.
    # See docs/plan-guest-shell.md.
    [ -x "$sys/sw/bin/ash" ] && ln -sf "$sys/sw/bin/ash" /bin/sh

    # nix-env default expr from the cache index (resolves `nix-env -iA <name>`).
    [ -f /nix-cache/pkgs.nix ] && cp /nix-cache/pkgs.nix /root/.nix-defexpr 2>/dev/null || true

    echo "pc: booting Nix userspace from $sys"
    exec "$sys/init"
  fi

  echo "pc: no Nix system found at /nix/var/nix/profiles/system — dropping to a shell"
  exec /bin/sh
''
