# The thin initramfs /init for the wasm guest, GENERATED by Nix and baked into
# .#wasm-initramfs. It is the only hand-shaped guest code, and it is irreducible:
# it must mount /nix before anything in the store is reachable.
#
# Roles (#177 — installed NixOS, not a live USB):
#   1. Mount pseudofs + pc's 9P exports.
#   2. Install vs installed:
#        • No install stamp on /dev/vdb → installer mode: mkfs the state disk,
#          copy seed /nix from squashfs (/dev/vda) onto vdb, write stamp.
#        • Stamp present → mount vdb's /nix directly (no squashfs overlay).
#        • No vdb (busybox / harness) → legacy squashfs+ramfs overlay fallback.
#   3. Run the closure's activation, then exec the closure's init.
#
# Run-in-place: no switch_root (NOMMU; the initramfs ramfs stays the root, so the
# baked /bin/sh persists).
#
# 9P: trans=virtio -> stock mainline net/9p/trans_virtio.c -> a host-side
# virtio-9p device (runtime/virtio/ninep-device.js) -> the JS 9P server.
# /nix seed is a squashfs image on /dev/vda (virtio-blk, #43); the installed
# store lives on /dev/vdb (VW_DEV_BLK_STATE, #177).
#
# nixpkgsChannel — the wasm-nixpkgs channel store path (baked into the squashfs
# via base-squashfs.nix). The guest's `nixpkgs` nix-env channel is `import
# <this path> {}`; null → no nixpkgs channel (busybox-only / toolchain-only boots).
#
# forkMode (#131 prove-then-flip) — this init runs on the software-MMU real-fork
# guest (.#kernel-mmu-a2 + busybox-fork). It selects the normal MMU shared-memory
# and 9P read paths, and skips the forkshell-ash promotion below.
{ pkgs, nixpkgsChannel ? null, forkMode ? false }:
pkgs.writeText "init" ''
  #!/bin/sh
  # busybox is on /bin (baked); call applets via PATH.
  export PATH=/bin:/sbin

  mount -t proc none /proc
  mount -t sysfs none /sys
  mount -t devtmpfs none /dev 2>/dev/null
  mkdir -p /dev/pts && mount -t devpts none /dev/pts 2>/dev/null

  # /dev/shm for POSIX shared memory. GTK/gdk's wayland backend allocates its
  # window buffers via open_shared_memory() → memfd_create(), which is ENOSYS on
  # the wasm kernel, so gdk falls back to shm_open("/dev/shm/..."); without this
  # mount that fails ENOENT → no wl_shm buffer → an empty (0x0) window + a per-frame
  # "Gdk-CRITICAL: create_shm_surface" (gtk-wayland-render-blocker). NOMMU must
  # use ramfs: it has the architecture's explicit MAP_SHARED implementation,
  # while mainline shmem/tmpfs is MMU-only. The real-MMU profile uses normal
  # tmpfs instead, so its shared-memory path no longer inherits a NOMMU-only
  # accommodation.
  mkdir -p /dev/shm && mount -t ${if forkMode then "tmpfs" else "ramfs"} none /dev/shm 2>/dev/null

  # Stock trans_virtio caps requests at 500 KiB (512000 bytes).
  M="trans=virtio,version=9p2000.L,msize=512000"
  # cache=loose + ignoreqv route 9p reads through the page cache (buffered) instead
  # of netfs UNBUFFERED/direct reads. Direct reads call iov_iter_extract_pages /
  # get_user_pages on the user buffer, which fails EFAULT on this NOMMU/wasm guest
  # ("netfs: Couldn't get user pages (rc=-14)") — that broke `nix-env -iA`. Buffered
  # reads fill kernel page-cache pages then copy_to_user (works). cache=none (the
  # default) forces P9L_DIRECT; so does qid.version==0 (which the JS 9p servers
  # report) unless ignoreqv is set — hence BOTH on NOMMU. MMU has working
  # get_user_pages(), so use the normal direct-read path there.
  RO="$M${pkgs.lib.optionalString (!forkMode) ",cache=loose,ignoreqv"}"

  # pc's VFS (user files) at /mnt/yore.
  mkdir -p /mnt/yore
  mount -t 9p -o "$M,aname=/" yoreroot /mnt/yore 2>/dev/null || echo "yore: /mnt/yore 9p mount failed"

  # #177 offline home: the appliance logs in as root, so make /root itself the
  # host-visible home instead of copying it out only at shutdown. Files written
  # here live directly under pc's /Home/Library/Linux/home and remain browsable
  # after the guest stops. Older/minimal harnesses without the prepared Linux
  # tree keep their initramfs-local /root.
  HOST_HOME=/mnt/yore/Home/Library/Linux/home
  if [ -d /mnt/yore/Home/Library/Linux ]; then
    mkdir -p "$HOST_HOME" /root
    mount --bind "$HOST_HOME" /root 2>/dev/null \
      && echo "yore: home=/root host=/Home/Library/Linux/home" \
      || echo "yore: host home bind failed"
  fi

  # Nix binary cache (substituter for `nix-env -iA`), read-only.
  mkdir -p /nix-cache
  mount -t 9p -o "$RO,aname=nixcache" nixcache /nix-cache 2>/dev/null || true

  # Hard, console-visible profile proof consumed by smoke.mjs. Check the actual
  # mounted filesystem/options, not merely the branch this generated script took.
  SHM_TYPE=$(stat -f -c %T /dev/shm 2>/dev/null)
  NIXCACHE_OPTS=$(awk '$2 == "/nix-cache" { print $4 }' /proc/mounts)
  ${pkgs.lib.optionalString forkMode ''
    case "$NIXCACHE_OPTS" in
      *cache=0xf*|*ignoreqv*) ;;
      *) [ "$SHM_TYPE" = tmpfs ] && echo "yore: profile-fs=mmu shm=tmpfs nixcache=direct" ;;
    esac
  ''}
  ${pkgs.lib.optionalString (!forkMode) ''
    CACHE_LOOSE= QV_IGNORED=
    case "$NIXCACHE_OPTS" in *cache=0xf*) CACHE_LOOSE=1 ;; esac
    case "$NIXCACHE_OPTS" in *ignoreqv*) QV_IGNORED=1 ;; esac
    [ "$SHM_TYPE" = ramfs ] && [ -n "$CACHE_LOOSE" ] && [ -n "$QV_IGNORED" ] \
      && echo "yore: profile-fs=nommu shm=ramfs nixcache=loose"
  ''}

  # ---- /nix: installed state disk vs seed installer vs legacy overlay --------
  # Stamp file written after a successful seed copy. Presence ⇒ mount vdb as /nix
  # directly (no squashfs overlay). Absence + empty vdb ⇒ install mode.
  STAMP=/.yore-linux-installed
  mkdir -p /nix /mnt/nix-ro /mnt/state

  mount_seed_overlay() {
    # Legacy / recovery: squashfs lower + ramfs upper (ephemeral). Used when no
    # state disk is attached, or install failed. NOT the persistence path.
    mkdir -p /run/nix-upper /run/nix-work
    if mount -t squashfs -o ro /dev/vda /mnt/nix-ro 2>/dev/null; then
      mount -t overlay overlay \
        -o lowerdir=/mnt/nix-ro,upperdir=/run/nix-upper,workdir=/run/nix-work /nix \
        || { echo "yore: /nix overlay failed; falling back to ramfs /nix"; mkdir -p /nix/store; }
    else
      echo "yore: served store not mounted; booting empty ramfs /nix"
      mkdir -p /nix/store
    fi
  }

  if [ -b /dev/vdb ]; then
    # /sys/block/vdb/size is capacity in 512-byte sectors. The host attaches a
    # 1 MiB shared stub when no real stateDisk was passed (CI harness); that is
    # far too small to hold the seed store. Treat anything under 64 MiB as
    # "not an install disk" and keep the legacy squashfs overlay so existing
    # smokes keep working. pc's real state disk is ≥1 GiB (see DEFAULT_STATE_DISK_BYTES).
    vdb_sectors=$(cat /sys/block/vdb/size 2>/dev/null || echo 0)
    # 64 MiB = 131072 * 512-byte sectors
    if [ "$vdb_sectors" -lt 131072 ]; then
      echo "yore: /dev/vdb harness stub (''${vdb_sectors} sectors) — legacy overlay"
      mount_seed_overlay
    else
      # Try to mount an already-installed state disk.
      if mount -t ext4 -o rw /dev/vdb /mnt/state 2>/dev/null \
         || mount -t ext2 -o rw /dev/vdb /mnt/state 2>/dev/null; then
        if [ -f "/mnt/state$STAMP" ] && [ -d /mnt/state/nix/store ]; then
          echo "yore: installed system on /dev/vdb — mounting /nix directly"
          # Bind the store tree to /nix (state disk root holds /nix + /home + stamp).
          if mount --bind /mnt/state/nix /nix; then
            NIX_ON_STATE=1
          else
            echo "yore: bind /nix from state disk failed"
            mount_seed_overlay
          fi
        else
          # Mounted but unstamped / incomplete — treat as needs (re)install.
          umount /mnt/state 2>/dev/null || true
          NEED_INSTALL=1
        fi
      else
        NEED_INSTALL=1
      fi

      if [ -n "$NEED_INSTALL" ]; then
        echo "yore: installing seed /nix onto /dev/vdb (first boot / reset)"
        # busybox mkfs.ext2 (CONFIG_MKFS_EXT2=y). EXT4 driver mounts the result.
        # Nix closures contain many tiny files, so the 4 KiB default wastes
        # hundreds of MiB in tail blocks. A 1 KiB block and one inode per 8 KiB
        # give this 1.75 GiB disk ~229k inodes while keeping the measured seed
        # near its ~1 GiB logical size. -m 1 retains a small recovery reserve.
        mkfs.ext2 -F -q -b 1024 -i 8192 -m 1 /dev/vdb \
          || { echo "yore: mkfs.ext2 /dev/vdb failed — falling back to seed overlay"; mount_seed_overlay; NEED_INSTALL=; }
      fi

      if [ -n "$NEED_INSTALL" ]; then
        if mount -t ext4 -o rw /dev/vdb /mnt/state 2>/dev/null \
           || mount -t ext2 -o rw /dev/vdb /mnt/state 2>/dev/null; then
          mkdir -p /mnt/state/nix /mnt/state/home /mnt/state/var
          if mount -t squashfs -o ro /dev/vda /mnt/nix-ro 2>/dev/null; then
            # Copy seed store + nix db/profiles onto the state disk. This is the
            # install step — after this, squashfs is irrelevant until Reset.
            #
            # Keep store paths as separate copy operations so a failure cannot
            # leave the remainder of one opaque tree looking installed. After
            # each path, sync the state filesystem and release only that path's
            # source/destination cache pages. This keeps the 2 GiB NOMMU guest
            # from retaining the whole expanded seed twice, without manipulating
            # the global VM drop_caches control.
            echo "yore: copying seed store (this may take a while)…"
            mkdir -p /mnt/state/nix/store
            COPY_FAIL=
            for p in /mnt/nix-ro/store/*; do
              [ -e "$p" ] || continue
              cp -a "$p" /mnt/state/nix/store/ || { COPY_FAIL=1; break; }
              base=''${p##*/}
              seed-cache-release /mnt/state "$p" "/mnt/state/nix/store/$base" \
                || { COPY_FAIL=1; break; }
            done
            if [ -z "$COPY_FAIL" ]; then
              for p in /mnt/nix-ro/*; do
                base=''${p##*/}
                [ "$base" = store ] && continue
                cp -a "$p" /mnt/state/nix/ || { COPY_FAIL=1; break; }
                seed-cache-release /mnt/state "$p" "/mnt/state/nix/$base" \
                  || { COPY_FAIL=1; break; }
              done
            fi
            [ -z "$COPY_FAIL" ] \
              && echo "yore: seed copy used bounded per-file page cache"
            if [ -n "$COPY_FAIL" ]; then
              echo "yore: seed copy failed"
              umount /mnt/nix-ro 2>/dev/null
              umount /mnt/state 2>/dev/null
              mount_seed_overlay
              NEED_INSTALL=
            fi
            umount /mnt/nix-ro 2>/dev/null || true
          else
            echo "yore: seed squashfs missing — cannot install"
            umount /mnt/state 2>/dev/null || true
            mount_seed_overlay
            NEED_INSTALL=
          fi
        else
          echo "yore: cannot mount freshly formatted /dev/vdb"
          mount_seed_overlay
          NEED_INSTALL=
        fi
      fi

      if [ -n "$NEED_INSTALL" ]; then
        # Stamp + bind /nix from the new install.
        date -u +"installed=%Y-%m-%dT%H:%M:%SZ" > "/mnt/state$STAMP" 2>/dev/null \
          || echo "installed=1" > "/mnt/state$STAMP"
        sync
        if mount --bind /mnt/state/nix /nix; then
          NIX_ON_STATE=1
          echo "yore: install complete — /nix is on /dev/vdb"
        else
          echo "yore: post-install bind /nix failed"
          mount_seed_overlay
        fi
      fi
    fi
  else
    # No state disk (pre-ABI-12 engine): legacy overlay.
    mount_seed_overlay
  fi

  # Migrate pre-generation installs in place. Older images used a direct
  # system -> /nix/store/... symlink. Preserve that selection as generation 1
  # so current disks gain normal Nix generation semantics without a reset.
  profile=/nix/var/nix/profiles/system
  if [ -n "$NIX_ON_STATE" ]; then
    legacy_system=$(readlink "$profile" 2>/dev/null || true)
    case "$legacy_system" in
      /nix/store/*)
        if [ ! -e /nix/var/nix/profiles/system-1-link ]; then
          ln -s "$legacy_system" /nix/var/nix/profiles/system-1-link
        fi
        ln -sfn system-1-link "$profile"
        echo "yore: migrated installed system profile to generation 1"
        ;;
    esac
  fi

  # Host-selected rollback. yore-pc writes selected.json only when it actually
  # chose a retained boot mirror for this boot. Synchronize the installed Nix
  # system profile to that same generation before activation, so rolling the
  # host kernel/initramfs back cannot accidentally activate newer userspace.
  # Validate mode + ABI against the selected generation's immutable manifest;
  # a stale or tampered selection is ignored rather than cross-booted.
  if [ -n "$NIX_ON_STATE" ] \
     && [ -f /mnt/yore/Home/Library/Linux/boot/selected.json ]; then
    selected=/mnt/yore/Home/Library/Linux/boot/selected.json
    selected_gen=$(sed -n 's/.*"generation"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p' \
      "$selected" | head -n 1)
    selected_mode=$(sed -n 's/.*"mode"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
      "$selected" | head -n 1)
    selected_abi=$(sed -n 's/.*"kernelAbi"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p' \
      "$selected" | head -n 1)
    selected_system=$(sed -n 's/.*"system"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
      "$selected" | head -n 1)
    case "$selected_gen" in *[!0-9]*|"") selected_gen= ;; esac
    case "$selected_mode" in mmu|nommu) ;; *) selected_gen= ;; esac
    case "$selected_abi" in *[!0-9]*|"") selected_gen= ;; esac
    if [ -n "$selected_gen" ]; then
      gen_link="/nix/var/nix/profiles/system-$selected_gen-link"
      gen_sys=$(readlink "$gen_link" 2>/dev/null || true)
      gen_manifest="$gen_sys/boot/manifest.json"
      gen_mode=$(sed -n 's/.*"mode"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
        "$gen_manifest" 2>/dev/null | head -n 1)
      gen_abi=$(sed -n 's/.*"kernelAbi"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p' \
        "$gen_manifest" 2>/dev/null | head -n 1)
      if [ -n "$gen_sys" ] && [ "$gen_sys" = "$selected_system" ] \
         && [ "$gen_mode" = "$selected_mode" ] \
         && [ "$gen_abi" = "$selected_abi" ]; then
        ln -sfn "system-$selected_gen-link" /nix/var/nix/profiles/system
        echo "yore: host selected system generation $selected_gen"
      else
        echo "yore: ignoring invalid host boot generation $selected_gen"
      fi
    fi
  fi

  # Auto-configure networking via DHCP before handing off to init, so BOTH the
  # nix-system path (exec "$sys/init") and the busybox-only path (exec /bin/sh)
  # come up networked. The host (pc tcpip.js) runs a DHCP server on the bridge
  # gateway 10.0.2.1/24; udhcpc gets us a 10.0.2.x lease and runs the lease
  # script (/usr/share/udhcpc/default.script) to set the address/route/DNS.
  #
  # NOMMU caveats (proven by the Task 2.5 node spike — see docs/2026-06-21-
  # guest-dhcp-spike.md). udhcpc's DHCP protocol AND its lease-script exec work
  # fine on this wasm NOMMU guest — the script runs via libbb spawn() ->
  # clone-with-a-fn (patch 0004). Two things DON'T work and we route around them:
  #   1. udhcpc's OWN `-b` daemonize (bb_daemonize_or_rexec) silently dies — with
  #      -b it never even sends a DISCOVER. So we use `-f` (stay foreground).
  #   2. Backgrounding udhcpc directly from THIS init with `&` and then
  #      `exec`-ing the next stage races the just-forked job away (no udhcpc in
  #      the process table afterwards). Wrapping the launch in `sh -c '... &'`
  #      detaches it into its own shell that fully spawns udhcpc before this init
  #      continues to the exec handoff — that survives and acquires the lease.
  # Flags: -f (foreground, no self-daemonize), -t 0 (retry DISCOVER forever — the
  # host DHCP server may not be up yet at boot), -A 2 (short inter-round wait).
  # No -q: udhcpc stays resident so it re-runs the lease script on renew. Guarded
  # on the NIC existing so a no-net kernel still boots.
  if [ -e /sys/class/net/eth0 ]; then
    sh -c 'ip link set eth0 up 2>/dev/null; udhcpc -i eth0 -f -t 0 -A 2 >/dev/null 2>&1 &'
  fi

  # Resolve + activate the system, then hand off to init. The whole toolchain
  # (nix + multi-call entry points, clang, wasm-ld, cc, make) is now part of the
  # activated system profile (/run/current-system/sw/bin, on PATH via /etc/profile)
  # — there is NO host-provided /opt/bin seam anymore.
  # Resolve the standard two-link Nix profile without realpath. musl realpath
  # has historically corrupted long overlay/9P targets in this guest.
  sys=$(readlink "$profile" 2>/dev/null)
  case "$sys" in
    /*) ;;
    "") ;;
    *) sys=$(readlink "/nix/var/nix/profiles/$sys" 2>/dev/null) ;;
  esac
  if [ -n "$sys" ] && [ -e "$sys/init" ]; then
    sh "$sys/activate" "$sys"

    # Promote the autoconf-capable forkshell ash to /bin/sh (the initramfs bakes
    # busybox hush there). This is a NOMMU-only accommodation, not a hush
    # capability gap: patches/busybox/0009+0010 (hush >&$fd / <&0 fixes) make
    # patched hush run a REAL generated `configure`/`config.status` end to
    # end — hush's old "ambiguous redirect" / "syntax error at 'fi'" death was
    # its parse-time rejection of the autoconf-generated ">&$4" construct
    # (as_fn_error's variable-fd redirect), not a POSIX-conformance gap in
    # general; see the patch headers for the root cause + upstream-unfixed
    # status. NOMMU hush isn't totally fork-free either — it carries its own
    # narrow clone-spawn conversions (0003-hush-cmdsub-clone +
    # 0006-hush-heredoc-clone, wired into busybox.nix) for $()/heredoc
    # specifically. What forkshell ash still uniquely provides on THIS
    # (NOMMU) guest is the GENERAL case — subshells and pipelines via full
    # serialize+re-exec, which hush's narrow conversions don't cover (real
    # fork() only exists on the software-MMU/fork guest, #131 Track B) — so
    # ash stays the promoted /bin/sh for autoconf on NOMMU until #131 slice 1
    # retires it in favor of hush (the fork guest already defaults to hush —
    # see busybox-fork.nix).
    # Relink after activation, once the served closure (and its ash) is
    # mounted. System services invoke the profile-absolute busybox sh
    # directly, so only `#!/bin/sh` scripts and the interactive login shell
    # pick up ash.
    # See CLAUDE.md (Architecture: guest userspace) + userspace/ash.nix comments.
    # forkMode: keep busybox-fork's hush as /bin/sh (see the header comment).
    ${pkgs.lib.optionalString (!forkMode) ''[ -x "$sys/sw/bin/ash" ] && ln -sf "$sys/sw/bin/ash" /bin/sh''}

    # nix-env channels (resolve `nix-env -iA <channel>.<name>`), real-NixOS-style.
    # Two channels in ~/.nix-defexpr (nix-env addresses each top-level dir as a
    # channel; access is lazy per channel, so installing a tool never forces the
    # nixpkgs side and vice-versa):
    #   wasm-tools — the on-demand toolchain catalog from the cache index
    #                (guest-cc / guest-cxx / guest-clang / make-wasm32): pkgs.nix.
    #   nixpkgs    — the pinned nixpkgs evaluated against the wasm crossSystem,
    #                served as a tree at /nix-cache/channel: `nix-env -iA nixpkgs.<pkg>`
    #                works for ANY package (substitutes the prebuilt wasm output when
    #                published; otherwise the realise fails, like any uncached pkg).
    rm -rf /root/.nix-defexpr
    mkdir -p /root/.nix-defexpr/wasm-tools /root/.nix-defexpr/nixpkgs
    [ -f /nix-cache/pkgs.nix ] && cp /nix-cache/pkgs.nix /root/.nix-defexpr/wasm-tools/default.nix 2>/dev/null || true
    ${pkgs.lib.optionalString (nixpkgsChannel != null) ''
      echo 'import ${nixpkgsChannel} { }' > /root/.nix-defexpr/nixpkgs/default.nix
    ''}

    echo "yore: booting Nix userspace from $sys"
    exec "$sys/init"
  fi

  echo "yore: no Nix system found at /nix/var/nix/profiles/system — dropping to a shell"
  exec /bin/sh
''
