# The thin initramfs /init for the wasm guest, GENERATED by Nix and baked into
# .#wasm-initramfs. It is the only hand-shaped guest code, and it is irreducible:
# it must mount the served /nix store before anything in the store is reachable.
# Roles: mount pseudofs + pc's 9P exports, overlay the read-only served store
# with a ramfs upper -> /nix, run the closure's activation, then exec the
# closure's init. The toolchain (nix/clang/wasm-ld/cc/make) is part of the served
# closure now — on PATH via the system profile, no host-provided /opt/bin seam.
# Run-in-place: no switch_root (NOMMU; the initramfs ramfs stays the root, so the
# baked /bin/sh persists).
#
# 9P: trans=virtio -> stock mainline net/9p/trans_virtio.c -> a host-side
# virtio-9p device (runtime/virtio/ninep-device.js) -> the JS 9P server. This is
# the #10 consolidation: the guest now looks like a standard virtualized Linux
# at the 9P layer (stock v9fs over a stock carrier), replacing the bespoke
# trans_cb SAB-ring transport. The device is selected by MOUNT TAG (the first
# `mount` arg: "pcroot" / "nixcache" — kernel patch 0018 + the host devices);
# aname still selects the server export. Exports (boot.js): "/"=pc VFS, nixcache.
# msize ~500K: 9pnet_virtio caps it at PAGE_SIZE*(VIRTQUEUE_NUM-3) (VIRTQUEUE_NUM
# is the driver's fixed 128), so requesting 512K negotiates to ~500K — on par
# with trans_cb's 512K (no regression). The 9P virtqueues are sized to 128
# entries (patch 0018) so a single msize-sized request's ~125-page scatter-gather
# list fits in one descriptor chain; the default 64-entry ring would overflow
# (-ENOSPC) on large reads like a nix-env NAR fetch.
# /nix is a squashfs image on /dev/vda (virtio-blk, #43) — not a 9P export.
{ pkgs }:
pkgs.writeText "init" ''
  #!/bin/sh
  # busybox is on /bin (baked); call applets via PATH.
  export PATH=/bin:/sbin

  mount -t proc none /proc
  mount -t sysfs none /sys
  mount -t devtmpfs none /dev 2>/dev/null
  mkdir -p /dev/pts && mount -t devpts none /dev/pts 2>/dev/null

  # /dev/shm for POSIX shared memory. GTK/gdk's wayland backend allocates its
  # window buffers via open_shared_memory() → memfd_create(), which is ENOSYS on
  # the wasm kernel, so gdk falls back to shm_open("/dev/shm/..."); without this
  # mount that fails ENOENT → no wl_shm buffer → an empty (0x0) window + a per-frame
  # "Gdk-CRITICAL: create_shm_surface" (gtk-wayland-render-blocker). Use RAMFS, not
  # tmpfs: ramfs has explicit NOMMU MAP_SHARED mmap support (fs/ramfs/file-nommu.c)
  # — the same backing /tmp uses (proven by the wl-anim shm client) — whereas
  # shmem/tmpfs lacks reliable shared-writable mmap on NOMMU.
  mkdir -p /dev/shm && mount -t ramfs none /dev/shm 2>/dev/null

  M="trans=virtio,version=9p2000.L,msize=524288"
  # cache=loose + ignoreqv route 9p reads through the page cache (buffered) instead
  # of netfs UNBUFFERED/direct reads. Direct reads call iov_iter_extract_pages /
  # get_user_pages on the user buffer, which fails EFAULT on this NOMMU/wasm guest
  # ("netfs: Couldn't get user pages (rc=-14)") — that broke `nix-env -iA`. Buffered
  # reads fill kernel page-cache pages then copy_to_user (works). cache=none (the
  # default) forces P9L_DIRECT; so does qid.version==0 (which the JS 9p servers
  # report) unless ignoreqv is set — hence BOTH. Read-only exports, so loose is safe.
  RO="$M,cache=loose,ignoreqv"

  # pc's VFS (user files) at /mnt/pc.
  mkdir -p /mnt/pc
  mount -t 9p -o "$M,aname=/" pcroot /mnt/pc 2>/dev/null || echo "pc: /mnt/pc 9p mount failed"

  # Nix binary cache (substituter for `nix-env -iA`), read-only.
  mkdir -p /nix-cache
  mount -t 9p -o "$RO,aname=nixcache" nixcache /nix-cache 2>/dev/null || true

  # The served base-system closure: a read-only squashfs on virtio-blk ->
  # overlay lower; ramfs upper makes /nix writable for nix-env. NOMMU has no
  # block-backed writable fs, so the upper is ramfs (as before).
  mkdir -p /mnt/nix-ro /run/nix-upper /run/nix-work /nix
  if mount -t squashfs -o ro /dev/vda /mnt/nix-ro 2>/dev/null; then
    mount -t overlay overlay \
      -o lowerdir=/mnt/nix-ro,upperdir=/run/nix-upper,workdir=/run/nix-work /nix \
      || { echo "pc: /nix overlay failed; falling back to ramfs /nix"; mkdir -p /nix/store; }
  else
    echo "pc: served store not mounted; booting empty ramfs /nix"
    mkdir -p /nix/store
  fi

  # Auto-configure networking via DHCP before handing off to init, so BOTH the
  # nix-system path (exec "$sys/init") and the busybox-only path (exec /bin/sh)
  # come up networked. The host (pc tcpip.js) runs a DHCP server on the bridge
  # gateway 10.0.2.1/24; udhcpc gets us a 10.0.2.x lease and runs the lease
  # script (/usr/share/udhcpc/default.script) to set the address/route/DNS.
  #
  # NOMMU caveats (proven by the Task 2.5 node spike — see docs/2026-06-21-
  # guest-dhcp-spike.md). udhcpc's DHCP protocol AND its lease-script exec work
  # fine on this wasm NOMMU guest — the script runs via libbb spawn() ->
  # clone-with-a-fn (patch 0004). Two things DON'T work and we route around them:
  #   1. udhcpc's OWN `-b` daemonize (bb_daemonize_or_rexec) silently dies — with
  #      -b it never even sends a DISCOVER. So we use `-f` (stay foreground).
  #   2. Backgrounding udhcpc directly from THIS init with `&` and then
  #      `exec`-ing the next stage races the just-forked job away (no udhcpc in
  #      the process table afterwards). Wrapping the launch in `sh -c '... &'`
  #      detaches it into its own shell that fully spawns udhcpc before this init
  #      continues to the exec handoff — that survives and acquires the lease.
  # Flags: -f (foreground, no self-daemonize), -t 0 (retry DISCOVER forever — the
  # host DHCP server may not be up yet at boot), -A 2 (short inter-round wait).
  # No -q: udhcpc stays resident so it re-runs the lease script on renew. Guarded
  # on the NIC existing so a no-net kernel still boots.
  if [ -e /sys/class/net/eth0 ]; then
    sh -c 'ip link set eth0 up 2>/dev/null; udhcpc -i eth0 -f -t 0 -A 2 >/dev/null 2>&1 &'
  fi

  # Resolve + activate the system, then hand off to init. The whole toolchain
  # (nix + multi-call entry points, clang, wasm-ld, cc, make) is now part of the
  # activated system profile (/run/current-system/sw/bin, on PATH via /etc/profile)
  # — there is NO host-provided /opt/bin seam anymore.
  # The profile symlink is a DIRECT absolute pointer to the store path (one level;
  # see store-manifest.py), so a plain readlink resolves it — no `-f`/realpath
  # canonicalization (musl realpath corrupts long targets read over 9p/overlay).
  sys=$(readlink /nix/var/nix/profiles/system 2>/dev/null)
  if [ -n "$sys" ] && [ -e "$sys/init" ]; then
    sh "$sys/activate" "$sys"

    # Promote the autoconf-capable forkshell ash to /bin/sh (the initramfs bakes
    # busybox hush there). hush isn't POSIX-enough for autoconf: a package's
    # ./configure and the config.status it generates carry a `#!/bin/sh` shebang,
    # so they run under whatever /bin/sh is. The forkshell ash (NOMMU-safe
    # subshell/$()/pipeline/heredoc via serialize+re-exec) parses autoconf; hush
    # dies with "ambiguous redirect" / "syntax error at 'fi'". Relink after
    # activation, once the served closure (and its ash) is mounted. System
    # services invoke the profile-absolute busybox sh directly, so only
    # `#!/bin/sh` scripts and the interactive login shell pick up ash.
    # See CLAUDE.md (Architecture: guest userspace) + userspace/ash.nix comments.
    [ -x "$sys/sw/bin/ash" ] && ln -sf "$sys/sw/bin/ash" /bin/sh

    # nix-env default expr from the cache index (resolves `nix-env -iA <name>`).
    [ -f /nix-cache/pkgs.nix ] && cp /nix-cache/pkgs.nix /root/.nix-defexpr 2>/dev/null || true

    # Seed the catalog packages' .drv closure into the Nix DB (codebutler/nix-wasm#1).
    # base.squashfs ships those .drv files + this registration; loading it makes the
    # .drvs read as VALID locally, so the NEW CLI (`nix profile install`) — which
    # realises Built{drvPath} and needs the .drv present (Nix never substitutes a
    # .drv from a cache: src/libstore/misc.cc queryMissing marks a non-local .drv
    # "unknown") — finds the deriver and substitutes the OUTPUT from /nix-cache.
    # Real-system store state (.drvs local as eval would have written them), reached
    # via `nix copy --derivation` rather than in-guest nixpkgs eval (#92).
    if [ -f /nix/.drv-registration ] && [ -x "$sys/sw/bin/nix-store" ]; then
      mkdir -p /nix/var/nix/db
      "$sys/sw/bin/nix-store" --load-db < /nix/.drv-registration 2>/dev/null \
        || echo "pc: nix-store --load-db (drv seed) failed"
    fi

    echo "pc: booting Nix userspace from $sys"
    exec "$sys/init"
  fi

  echo "pc: no Nix system found at /nix/var/nix/profiles/system — dropping to a shell"
  exec /bin/sh
''
