# wasm-nixpkgs-channel.nix — the in-guest "nixpkgs" channel: the pinned nixpkgs
# evaluated against the wasm crossSystem, so the guest can `nix-env -iA
# nixpkgs.<any package>` exactly like a real NixOS system, not just the 4-entry
# toolchain catalog.
#
# WHY this is coherent (the key insight): `wasm-cross.nix` takes an explicit
# `localSystem` and the cross derivations are host-agnostic, so EVAL is pure and
# architecture-independent. With `localSystem` PINNED to the build host (the
# CI/publish host), the guest computes the SAME `cross.<pkg>` .drv hashes the host
# builds, then substitutes the host's prebuilt output. Proven in-guest: `cross.hello`
# / `cross.file` evaluate to wasm32 .drvs in ~15s within the ~2 GiB cap
# (docs/superpowers/notes/2026-06-28-nixpkgs-in-guest-eval.md).
#
# Delivery (no kernel/ABI change): this derivation is a SMALL tree (the cross config
# + a generated `default.nix`, ~1.3 MB) baked into the base squashfs (base-squashfs.nix
# adds it as a closure root) — a real on-disk dir so directory traversal works, unlike
# the flat binary-cache 9P export. The guest's `~/.nix-defexpr/nixpkgs` is `import
# <this store path> {}` (bootstrap.nix bakes the path).
#
# The pinned nixpkgs source is deliberately fetched by default.nix only when this
# channel is evaluated. Putting its /nix/store path in the system environment made
# closureInfo seed the entire source tree: 52,840 files consumed ~338 MiB of 4 KiB
# ext2 blocks and pushed the 1.75 GiB browser state disk into ENOSPC on first boot.
# `fetchTarball` keeps ordinary boot/toolchain use small while retaining the normal
# `nix-env -iA nixpkgs.<pkg>` behavior. The source is pinned by both revision and NAR
# hash, and the public binary cache roots the same source for reproducibility.
#
# The set returned is exactly `cross` (the wasm cross package set). The wasm-specific
# toolchain (guest-cc/guest-cxx/guest-clang/make-wasm32) stays in its own `wasm-tools`
# channel — it is NOT a nixpkgs package, so it does not belong in the nixpkgs channel.
#
# self        — the flake source (for the cross config files; `${self}/toolchain`…)
# localSystem    — the build/publish host system, pinned so guest .drv hashes match.
# nixpkgsRev     — exact flake input revision used by the host build.
# nixpkgsNarHash — exact normalized source hash for the lazy guest fetch.
{ pkgs, self, localSystem, nixpkgsRev, nixpkgsNarHash }:
pkgs.runCommand "wasm-nixpkgs-channel" { } ''
  mkdir -p $out
  cp -r ${self}/toolchain ${self}/patches ${self}/userspace $out/
  cp ${self}/wasm-cross.nix ${self}/deps-overlay.nix $out/
  chmod -R u+w $out

  cat > $out/default.nix <<NIXEOF
  # GENERATED by userspace/wasm-nixpkgs-channel.nix — the guest's `nixpkgs` channel
  # default expression. Returns the wasm cross package set: `nix-env -iA nixpkgs.<pkg>`.
  { system ? "${localSystem}" }:
  let
    # Do not bake the resulting source store path into the boot closure. It is
    # fetched/realised only when a user evaluates this channel.
    nixpkgs = builtins.fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/${nixpkgsRev}.tar.gz";
      sha256 = "${nixpkgsNarHash}";
    };
    pkgs = import nixpkgs { inherit system; };
    compilerRt = import ./toolchain/compiler-rt.nix { inherit pkgs; };
    musl = import ./toolchain/musl.nix { inherit pkgs compilerRt; };
    kernelHeaders = import ./toolchain/kernel-headers.nix { inherit pkgs; };
    libcxx = import ./toolchain/libcxx.nix { inherit pkgs musl kernelHeaders compilerRt; };
    sysroot = import ./toolchain/sysroot.nix { inherit pkgs musl kernelHeaders; };
  in
  import ./wasm-cross.nix {
    inherit nixpkgs sysroot compilerRt libcxx;
    localSystem = system;
    overlays = [ (import ./deps-overlay.nix { inherit kernelHeaders; muslWasm = musl; }) ];
  }
  NIXEOF
''
